// filename: RecipeFormPage.tsx — Code Generated by Sidekick is for learning and experimentation purposes only.

import { useState, type ChangeEvent, type FormEvent } from 'react';
import type { Recipe } from './Dashboard';
import './Dashboard.css';

type RecipeFormPageProps = {
  initialRecipe?: Recipe;
  onSave: (recipe: Recipe) => void;
  onCancel: () => void;
};

function createEmptyRecipe(): Recipe {
  return {
    id: '',
    title: '',
    ingredients: '',
    instructions: '',
    tags: [],
    image: '',
    createdAt: new Date().toISOString(),
  };
}

export default function RecipeFormPage({
  initialRecipe,
  onSave,
  onCancel,
}: RecipeFormPageProps) {
  const startingRecipe = initialRecipe
    ? { ...initialRecipe, tags: [...initialRecipe.tags] }
    : createEmptyRecipe();

  const [draft, setDraft] = useState<Recipe>(startingRecipe);
  const [showUnsavedModal, setShowUnsavedModal] = useState(false);
  const [titleError, setTitleError] = useState('');

  const isEditing = Boolean(initialRecipe);
  const hasChanges = JSON.stringify(draft) !== JSON.stringify(startingRecipe);

  function updateField(field: keyof Recipe, value: string | string[]) {
    setDraft((current) => ({
      ...current,
      [field]: value,
    }));
  }

  function saveRecipe() {
    if (!draft.title.trim()) {
      setTitleError('Title is required');
      return;
    }

    onSave({
      ...draft,
      id: draft.id || Date.now().toString(),
      title: draft.title.trim(),
      tags: draft.tags.filter(Boolean),
    });
  }

  function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    saveRecipe();
  }

  function handleCancel() {
    if (hasChanges) {
      setShowUnsavedModal(true);
    } else {
      onCancel();
    }
  }

  function handleImageChange(event: ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0];

    if (!file) return;

    const reader = new FileReader();

    reader.onload = () => {
      if (typeof reader.result === 'string') {
        updateField('image', reader.result);
      }
    };

    reader.readAsDataURL(file);
  }

  return (
    <main className="recipe-form-page">
      <section className="recipe-form-content">
        <h1>{isEditing ? 'Edit a Recipe' : 'Create a Recipe'}</h1>

        <form onSubmit={handleSubmit}>
          <label>
            Title
            <input
              className={titleError ? 'input-error' : ''}
              onChange={(event) => {
                setTitleError('');
                updateField('title', event.target.value);
              }}
              value={draft.title}
            />
          </label>

          {titleError && <p className="error-message">{titleError}</p>}

          <label>
            Ingredients
            <textarea
              onChange={(event) =>
                updateField('ingredients', event.target.value)
              }
              value={draft.ingredients}
            />
          </label>

          <label>
            Instructions
            <textarea
              onChange={(event) =>
                updateField('instructions', event.target.value)
              }
              value={draft.instructions}
            />
          </label>

          <label>
            Tags
            <input
              onChange={(event) =>
                updateField(
                  'tags',
                  event.target.value
                    .split(',')
                    .map((tag) => tag.trim()),
                )
              }
              value={draft.tags.join(', ')}
            />
          </label>

          <label>Image</label>

          <div className="image-preview">
            {draft.image ? (
              <img src={draft.image} alt="Recipe preview" />
            ) : (
              <span>No image selected</span>
            )}
          </div>

          <div className="image-actions">
            {draft.image && (
              <button
                className="image-button"
                onClick={() => updateField('image', '')}
                type="button"
              >
                Delete
              </button>
            )}

            <label className="image-button">
              Edit
              <input
                accept="image/*"
                hidden
                onChange={handleImageChange}
                type="file"
              />
            </label>
          </div>

          <button className="primary-button" type="submit">
            Save
          </button>

          <button
            className="secondary-button"
            onClick={handleCancel}
            type="button"
          >
            Cancel
          </button>
        </form>
      </section>

      {showUnsavedModal && (
        <div className="modal-backdrop">
          <div className="modal-card">
            <h2>You have unsaved changes.</h2>
            <p>Do you want to proceed without saving your changes?</p>

            <button className="primary-button" onClick={saveRecipe} type="button">
              Save Changes
            </button>

            <button
              className="secondary-button"
              onClick={onCancel}
              type="button"
            >
              Continue without Saving
            </button>

            <button
              className="text-button"
              onClick={() => setShowUnsavedModal(false)}
              type="button"
            >
              Cancel
            </button>
          </div>
        </div>
      )}
    </main>
  );
}
